[package]
name = "os"
version = "0.1.0"
authors = ["xuke <xuke0931@qq.com>"]
edition = "2021"

[dependencies]
sbi-rt = { version = "0.0.2", features = ["legacy"] }
log = "0.4"

[profile.release]
debug = true